apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fdotnetcorewebapp-deployment-${APP_VERSION}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fdotnetcorewebapp
        version: ${APP_VERSION}
    spec:
      containers:
      - name: fdotnetcorewebapp-pod
        image: fredcontainerregistry.azurecr.io/fdotnetcorewebapp:${APP_VERSION}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: fredcontainerregistry
